// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sam_LocalSuperMarket_OnlineShoppingStore1.Data;

#nullable disable

namespace Sam_LocalSuperMarket_OnlineShoppingStore1.Migrations
{
    [DbContext(typeof(SamOnlineShoppingStoreDBContext))]
    [Migration("20240425050300_initial Migrations")]
    partial class initialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$QE3SGagGwvzlSAmZhE6o8uqzFhfwP2bfwQFZtVJBnpB1rDDJITVB.",
                            Role = "User1",
                            UserName = "Test"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$DuWV/7qPhBJH5KXd5CRMIuTzS16PPQm4n0xJjM3/T1Nksot8/FPqG",
                            Role = "User2",
                            UserName = "Test1"
                        });
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Baked",
                            ImageCategory = "Baked"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Beverage",
                            ImageCategory = "Beverage"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "ColdMeat",
                            ImageCategory = "ColdMeat"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Dairy",
                            ImageCategory = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "FreshFoods",
                            ImageCategory = "FreshFoods"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Frozen",
                            ImageCategory = "Frozen"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Pantry",
                            ImageCategory = "Pantry"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "SelfCare",
                            ImageCategory = "SelfCare"
                        });
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageName = "Baked1",
                            ItemName = "Arnott's Scotch Finger",
                            Price = 2.8500000000000001,
                            Unit = "250 g"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageName = "Baked2",
                            ItemName = "Arnott's TimTam Original Chocolate",
                            Price = 3.6499999999999999,
                            Unit = "200 g"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageName = "Baked3",
                            ItemName = "Cheddar Shapes",
                            Price = 2.0,
                            Unit = "175 g"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImageName = "Baked4",
                            ItemName = "Helga's Wholemeal Bread",
                            Price = 3.7000000000000002,
                            Unit = "1 pk"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ImageName = "Baked5",
                            ItemName = "Weet Bix Saniatatium",
                            Price = 5.3300000000000001,
                            Unit = "750 g"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ImageName = "Beverage1",
                            ItemName = "Berri Orange Juice",
                            Price = 6.0,
                            Unit = "2 Litre"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ImageName = "Beverage2",
                            ItemName = "Coca Cola",
                            Price = 2.8500000000000001,
                            Unit = "2 Litre"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            ImageName = "ColdMeat1",
                            ItemName = "Macro Free Range Chicken",
                            Price = 7.5,
                            Unit = "1 kg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            ImageName = "ColdMeat2",
                            ItemName = "Primo English Ham",
                            Price = 3.0,
                            Unit = "100 g"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            ImageName = "ColdMeat3",
                            ItemName = "Primo Short Cut Rindless Bacon",
                            Price = 5.0,
                            Unit = "175 g"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            ImageName = "Dairy1",
                            ItemName = "A2 Light Milk",
                            Price = 2.8999999999999999,
                            Unit = "1 Litre"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            ImageName = "Dairy2",
                            ItemName = "Babybel Mini",
                            Price = 4.2000000000000002,
                            Unit = "100 g"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            ImageName = "Dairy3",
                            ItemName = "Bega Farmers Tasty",
                            Price = 4.0,
                            Unit = "250 g"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            ImageName = "Dairy4",
                            ItemName = "Chobani Strawbery Yoghurt",
                            Price = 1.5,
                            Unit = "140 g"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            ImageName = "Dairy5",
                            ItemName = "Lurpak Salted Blend",
                            Price = 5.0,
                            Unit = "250 g"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            ImageName = "Dairy6",
                            ItemName = "Manning Valley Eggs",
                            Price = 3.6000000000000001,
                            Unit = "6-pk"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            ImageName = "Dairy7",
                            ItemName = "Philadelphia Original Cream Cheese",
                            Price = 4.2999999999999998,
                            Unit = "250 g"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            ImageName = "Dairy8",
                            ItemName = "South Cape Greek Feta",
                            Price = 5.0,
                            Unit = "200 g"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            ImageName = "FreshFoods1",
                            ItemName = "Carrots",
                            Price = 2.0,
                            Unit = "1 kg"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            ImageName = "FreshFoods2",
                            ItemName = "Cucumber",
                            Price = 1.8999999999999999,
                            Unit = "1 whole"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            ImageName = "FreshFoods3",
                            ItemName = "Fresh Tomato",
                            Price = 5.9000000000000004,
                            Unit = "500 g"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            ImageName = "FreshFoods4",
                            ItemName = "Granny Smith's Apples",
                            Price = 5.5,
                            Unit = "1 kg"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            ImageName = "FreshFoods5",
                            ItemName = "Iceberg Lettuce",
                            Price = 2.5,
                            Unit = " 1 whole"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            ImageName = "FreshFoods6",
                            ItemName = "Red Onion",
                            Price = 3.5,
                            Unit = "1 kg"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            ImageName = "FreshFoods7",
                            ItemName = "Red Potato Washed",
                            Price = 4.0,
                            Unit = "1 kg"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            ImageName = "FreshFoods8",
                            ItemName = "Red Tipped Bananas",
                            Price = 4.9000000000000004,
                            Unit = "1 kg"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            ImageName = "FreshFoods9",
                            ItemName = "Watermelon",
                            Price = 6.5999999999999996,
                            Unit = "1 whole"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            ImageName = "Frozen1",
                            ItemName = "Birds Eye Fish Fingers",
                            Price = 4.5,
                            Unit = "375 g"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 7,
                            ImageName = "Pantry01",
                            ItemName = "Cadburry Dairy Milk",
                            Price = 5.0,
                            Unit = "200 g"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 7,
                            ImageName = "Pantry02",
                            ItemName = "Capilano Squeezable Honey",
                            Price = 7.3499999999999996,
                            Unit = "500 g"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            ImageName = "Pantry03",
                            ItemName = "Cobram Extra Virgin Olive Oil",
                            Price = 8.0,
                            Unit = "375 ml"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 7,
                            ImageName = "Pantry04",
                            ItemName = "Golden Circle Pineapple Pieces in natural juice",
                            Price = 3.25,
                            Unit = "440 g"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            ImageName = "Pantry05",
                            ItemName = "Heinz Tomato Soup",
                            Price = 2.5,
                            Unit = "535 g"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 7,
                            ImageName = "Pantry06",
                            ItemName = "John West Tuna can",
                            Price = 1.5,
                            Unit = "95 g"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            ImageName = "Pantry07",
                            ItemName = "Lindt Excellence 70% cocoa Block",
                            Price = 4.25,
                            Unit = "100 g"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 7,
                            ImageName = "Pantry08",
                            ItemName = "Milo Chocolate Malt",
                            Price = 4.0,
                            Unit = "200 g"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 7,
                            ImageName = "Pantry09",
                            ItemName = "Moccana Classic Instant Medium Roast",
                            Price = 6.0,
                            Unit = "100 g"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 7,
                            ImageName = "Pantry10",
                            ItemName = "Nutella Jar",
                            Price = 4.0,
                            Unit = "400 g"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 7,
                            ImageName = "Pantry11",
                            ItemName = "Sacla Pasta Tomato Basil Sauce",
                            Price = 4.5,
                            Unit = "420 g"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            ImageName = "Pantry12",
                            ItemName = "San Remo Linguine Pasta No. 1",
                            Price = 1.95,
                            Unit = "500 g"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 7,
                            ImageName = "Pantry13",
                            ItemName = "Smith's Original Share Pack Crisps",
                            Price = 3.29,
                            Unit = "170 g"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 7,
                            ImageName = "Pantry14",
                            ItemName = "Vegemite",
                            Price = 6.0,
                            Unit = "380 g"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 8,
                            ImageName = "SelfCare1",
                            ItemName = "Colgate Total Toothpaste Original",
                            Price = 3.5,
                            Unit = "110 g"
                        });
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalised")
                        .HasColumnType("bit");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 4, 25, 15, 3, 0, 427, DateTimeKind.Local).AddTicks(5105),
                            IsCancelled = false,
                            IsFinalised = false,
                            Total = 25.0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductsId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductsId = 1,
                            Quantity = 1,
                            ShoppingCartId = 1
                        });
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.Products", b =>
                {
                    b.HasOne("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ShoppingCart", b =>
                {
                    b.HasOne("Sam_LocalSuperMarket_OnlineShoppingStore1.Data.User", "CartUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartUser");
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.Products", "ProductsItem")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ShoppingCart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductsItem");
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.Products", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Sam_LocalSuperMarket_OnlineShoppingStore1.Models.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
